# Generated by Django 4.2.6 on 2023-11-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfitPilotApp', '0004_period_transactions_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period_transactions',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProfitPilotApp.types_transactions'),
        ),
    ]
